name: compare tsc and tslint findings
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: actions/checkout@v2
      name: Check out repository
    - run: |
        npm install
        npm run compare
